"use client";
export const dynamic = "force-dynamic";
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { formatCurrency } from "@/lib/utils";
export default function AdminDashboard() {
  const router = useRouter(); const [loading, setLoading] = useState(true); const [isAdmin, setIsAdmin] = useState(false);
  const [stats, setStats] = useState({ users: 0, workers: 0, bookings: 0, jobs: 0, revenue: 0 });
  useEffect(() => { (async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session?.user) { router.push("/login"); return; } const { data: p } = await supabase.from("profiles").select("role").eq("id", session.user.id).single(); if (p?.role !== "admin") { setIsAdmin(false); setLoading(false); return; } setIsAdmin(true); const [u, b, j] = await Promise.all([supabase.from("profiles").select("id, role").limit(100), supabase.from("bookings").select("platform_fee").limit(100), supabase.from("jobs").select("id").limit(100)]); setStats({ users: u.data?.length || 0, workers: u.data?.filter((x: any) => x.role === "seller" || x.role === "both").length || 0, bookings: b.data?.length || 0, jobs: j.data?.length || 0, revenue: b.data?.reduce((s: number, x: any) => s + (x.platform_fee || 0), 0) || 0 }); setLoading(false); })(); }, [router]);
  if (loading) return <div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh", background: "#07070D", color: "#F0F0F8" }}>Loading...</div>;
  if (!isAdmin) return <div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh", background: "#07070D", color: "#F0F0F8", textAlign: "center" }}><div><p style={{ fontSize: 32 }}>🔒</p><h2>Admin Only</h2><p style={{ color: "#9595B0", margin: "8px 0 16px", fontSize: 14 }}>Set role='admin' in Supabase profiles</p><button onClick={() => router.push("/home")} style={{ padding: "10px 20px", background: "#00E5B0", color: "#07070D", border: "none", borderRadius: 12, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" }}>Go Home</button></div></div>;
  const cards = [{ n: stats.users, l: "Users", c: "#00E5B0" },{ n: stats.workers, l: "Workers", c: "#5B8DEF" },{ n: stats.bookings, l: "Bookings", c: "#FFB636" },{ n: stats.jobs, l: "Jobs", c: "#A855F7" },{ n: formatCurrency(stats.revenue), l: "Revenue", c: "#FF4D6A" }];
  return <div style={{ minHeight: "100vh", background: "#07070D", color: "#F0F0F8", padding: 20 }}><div style={{ maxWidth: 600, margin: "0 auto" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }}><h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: 24 }}>👑 Admin</h1><button onClick={() => router.push("/home")} style={{ background: "rgba(20,20,35,0.7)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 10, padding: "8px 14px", color: "#9595B0", cursor: "pointer", fontFamily: "inherit", fontSize: 13, backdropFilter: "blur(20px)" }}>← Back</button></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 10 }}>{cards.map((s, i) => <div key={i} style={{ background: "rgba(20,20,35,0.7)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 18, padding: 16, backdropFilter: "blur(20px)" }}><div style={{ fontFamily: "'Playfair Display', serif", fontSize: 22, color: s.c }}>{s.n}</div><div style={{ fontSize: 12, color: "#9595B0", marginTop: 4 }}>{s.l}</div></div>)}</div></div></div>;
}
